name: Mastery Quotient Check
on:
  push:
    branches:
      - master
jobs:
  check-style-MastQuo:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone project
        uses: actions/checkout@v2

      - name: Set version asp
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Install StyleCop.Analyzers
        run: dotnet add package StyleCop.Analyzers --version 1.1.118 --package-directory ./.nuget/packages

      - name: Check Style
        run: dotnet build /p:ValidateStyleCopSettings=true /p:StyleCopCachePath=./.stylecop-cache